"""new column hashed password

Revision ID: 26a1b4a630c4
Revises: 2827f7950baf
Create Date: 2024-05-02 21:38:45.424233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a1b4a630c4'
down_revision: Union[str, None] = '2827f7950baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'hashed_password')
    # ### end Alembic commands ###
